export const ShiftsActionTypes = {
  GET_ORGANISATION_USERS: "GET_ORGANISATION_USERS",
  GET_SHIFTS: "GET_SHIFTS",
  ADD_SHIFT: "ADD_SHIFT",
  EDIT_SHIFT: "EDIT_SHIFT",
  REMOVE_SHIFT: "REMOVE_SHIFT",
  FETCH_ERROR: "FETCH_ERROR",
  CLEAR_SHIFTS: "CLEAR_SHIFTS",
};
