export const UserActionTypes = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",
  CLEAR_USER: "CLEAR_USER",
  CREATE_JOIN_ORGANISATION: "CREATE_JOIN_ORGANISATION",
  JOIN_ORGANISATION: "JOIN_ORGANISATION",
};
